### ISSUE TITLE
All the demo examples are deprecated. Unable to get any help

### ISSUE THREAD

**Issue by SidRathi47** [GetStream/website-react-examples#24]
Hi, I am really in a bad situation right now.
I have tried reading the docs, I need to create a team chat system. 
I tried to run your demo example. It worked but when I integrated it in my project I got this erro
```
./src/components/studentDashboard/chatContainer/components/PinnedMessageList/PinnedMessageList.js
Attempted import error: 'ChannelContext' is not exported from 'stream-chat-react'.
```
I am still not sure what could be the problem. But then I noticed the package versions.
Your example is at 
```
"stream-chat": "^2.12.0",
"stream-chat-react": "^3.1.2",
```
And my current project is at latest. 
```
 "stream-chat": "^3.10.0",
"stream-chat-react": "^6.0.2",
```
What can I do, Can anyone please just  help me? I only need some guidance on how to build custom components for team chat example.

**Comment by DanC5** [comment]
@SidRathi47 sorry for the late response, I didn't have notifications set up for this repo. Anyways, we're in the process of updating the example apps and all should be released soon. I already pushed up the gaming demo conversion, and the others will be live within the next day or two.

I'm going to close this issue as they'll be updated soon, but I'm now notified on issues here so feel free to reach out again as needed. Thanks.
