### ISSUE TITLE
website-react-examples/social-messenger throws an exception

### ISSUE THREAD

**Issue by dpetrov** [GetStream/website-react-examples#30]
I am trying to get the social-messenger example running. After setting the tokens correctly, the App throws an exception each time I am trying to send a message:

SyntaxError: Failed to execute 'postMessage' on 'Window': Invalid target origin '' in a call to 'postMessage'.

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/82677/124940888-06eb0c80-e013-11eb-8545-7f5ca5efd826.png">

Any thoughts?

**Comment by DanC5** [comment]
Hey @dpetrov, comment out these lines and you should be good to go, https://github.com/GetStream/website-react-examples/blob/master/social-messenger/src/App.js#L59-#L73. They are for communicating with our website.

**Comment by hien-h-tran** [comment]
Hello @DanC5 , 

I am having the same issue as the original poster on the Social Messenger TS version.  The app loads fine, and I can send and receive messages, but every time I tap the send button, I get the same issue: 

````
ERROR
Failed to execute 'postMessage' on 'Window': Invalid target origin '' in a call to 'postMessage'.
````

I haven't made any changes to the application, other then the development file.
