### ISSUE TITLE
Question: How do you modify the inline `ChatAutocomplete` height?

### ISSUE THREAD

**Issue by billpull** [GetStream/website-react-examples#34]
I have looked through the docs and have a conversation with support but I can't figure out how these demos were able to achieve different values for the inline height style on the chat input?

Social Messenger:  `style="height: 38px !important;"`
Team Chat Demo:  `style="height: 49px !important;"`    
Live Stream:   `style="height: 52px !important;"` 

I want to make the input much smaller in my application as well but based on the docs I find myself ending up having to re-implement all the features of `ChatAutoComplete`, which is leading to an unknown amount of feature gaps that I am sacrificing for better style. I noticed for instance the [social messaging input](https://github.com/GetStream/website-react-examples/blob/c528dab6ea6eb66b04cc33b35a0d27e1772b97fa/social-messenger-ts/src/components/MessagingInput/MessagingInput.tsx#L103) still uses `ChatAutoComplete`.

**Comment by zacheryconverse** [comment]
Hi Bill,

Thanks for reaching out. These height values aren't hardcoded inline - They are coming from our overrides of the [Textarea](https://github.com/GetStream/stream-chat-react/blob/751ba40b6d12871d2a29a528995d950a22fe242a/src/components/AutoCompleteTextarea/Textarea.js#L3) we use from '[react-textarea-autosize](https://www.npmjs.com/package/react-textarea-autosize)'

If you would like to make a smaller input, you should be able to override the min-height from [textarea](https://github.com/GetStream/website-react-examples/blob/c528dab6ea6eb66b04cc33b35a0d27e1772b97fa/social-messenger-ts/src/components/MessagingInput/MessagingInput.css#L50)

I'm going to close this issue, as it is intended for feature request, bugs, and the like. If you do have any more questions, please continue to communicate with our support - they are more than happy to be of any help at all. Cheers
