### ISSUE TITLE
Ability to get the selected channel when using ChannelList component

### ISSUE THREAD

**Issue by jaydeepw** [GetStream/website-react-examples#45]
Hi, I am working to integrate streamchat into one of my web applications using react.

```
<Chat client={chatClient} theme={`messaging ${theme}`}>
      <div id='mobile-channel-list' onClick={toggleMobile}>
        <ChannelList
          filters={filters}
          sort={sort}
          options={options}
        />
      </div>
      <div>
        <Channel
          Input={MessagingInput}
          maxNumberOfFiles={10}
          Message={CustomMessage}
          multipleUploads={true}
          ThreadHeader={MessagingThreadHeader}
          TypingIndicator={() => null}
        >
          {isCreating && (
            <CreateChannel toggleMobile={toggleMobile} onClose={() => setIsCreating(false)} />
          )}
          <GiphyContext.Provider value={giphyContextValue}>
            <ChannelInner theme={theme} toggleMobile={toggleMobile} />
          </GiphyContext.Provider>
        </Channel>
      </div>
    </Chat>
```

For `ChannelList`, I want a callback something like `onSelected` where I can get a selected channel and make use of it for the Channel component. Is this possible?

**Comment by zacheryconverse** [comment]
Hello and thanks for submitting an issue to our GitHub repository. We’re glad you’re getting hands on with the product. What you're looking for is our [setActiveChannel](https://getstream.io/chat/docs/sdk/react/custom-code-examples/channel_list_preview/#the-preview-prop-component) you can see here in the docs.

The Issue section of this Github repo is now reserved only for bug reports and feature improvements and suggestions. It looks like what you’re looking for is technical support using the product. For this support, we would suggest emailing our Customer Success and Engineer support team at support@getstream.io with your application key or ID and we’ll be able to help you out. Thanks for your understanding, we’re going to mark this issue as closed. In case our understanding is incorrect and you are describing a bug, we apologize, and invite you to please follow up with a minimal reproduction of the bug and we will reopen the issue and investigate accordingly.
