### ISSUE TITLE
feat: upgrade apps to stream-chat-react v10

### ISSUE THREAD

**Issue by MartinCupela** [GetStream/website-react-examples#65]
**Motivation**

Introduce the latest fixes and features into the demo apps.

**Comment by carmona** [comment]
Hey @MartinCupela, I just came across something similar to #66, most of what I see on the docs doesn't really apply to v10, and the examples are all good but using v6 so not really helpful.

Is there any planned release date for these updated docs/examples? Or is there any other support channel I could contact for updated docs?

**Comment by MartinCupela** [comment]
Hey @carmona, the upgrade of the apps is in progress. Two of them are already upgraded to v10.3.0:
- https://github.com/GetStream/website-react-examples/pull/68
- https://github.com/GetStream/website-react-examples/pull/67

Today another [PR](https://github.com/GetStream/website-react-examples/pull/69) has been added.

**Comment by carmona** [comment]
@MartinCupela that's great, thank you! Are the docs pages going to be updated as well? Would be nice to know at least which version the docs refer to.

eg. this one https://getstream.io/chat/docs/sdk/react/customization/input_ui/ has outdated code but it took me a while to understand it didn't reflect what's on v10

**Comment by MartinCupela** [comment]
@carmona we surely want to improve the documentation. It will be more of an ongoing effort. You can help us by reporting parts, that are outdated.
