### ISSUE TITLE
MessageTeam not found in stream-chat-react

### ISSUE THREAD

**Issue by whoisasey** [GetStream/website-react-examples#66]
Hi!

I'm currently following [this tutorial ](https://youtu.be/MJzbJQLGehs) on building a chat messaging app, and I've also looked to [this demo](https://github.com/GetStream/website-react-examples/tree/master/team-ts) for assistance.

When I try to import MessageTeam from steam-chat-react, I get this error in my browser:
![Screen Shot 2022-09-23 at 5 48 48 PM](https://user-images.githubusercontent.com/56001902/192061304-ae0b900c-58ee-46f4-bb93-da641e505221.png)

This is how I'm importing the export:
`import {
	Channel,
	useChatContext,
	MessageTeam,
} from 'stream-chat-react';`

and using it like this:
`<ChannelMessage={(messageProps, i) => (<MessageTeam key={i} {...messageProps} />`

Is this export deprecated? If so, is there another option?

Thanks!

**Comment by oliverlaz** [comment]
Hi @whoisasey,

Recently we released `stream-chat-react@10.0.0` which brings updated visuals and better theme customization options. Among these changes, `MessageTeam` has been removed as it was deprecated for a while now. You can read more about it here:
- https://getstream.io/blog/new-chat-theming-api-for-angular-and-react/
- https://getstream.io/chat/docs/sdk/react/release-guides/upgrade-to-v10/

We are currently updating these demos to match the new capabilities introduced with v10 of our SDK. You can track the progress with #65.

In meantime, you can take the code from our v9 release branch and copy it into your project (although I'm not sure whether this approach will work out of the box):
- https://github.com/GetStream/stream-chat-react/blob/release-v9/src/components/Message/MessageTeam.tsx

Another possibility would be to write your own Message UI:
- https://getstream.io/chat/docs/sdk/react/message-components/message_ui/

As a last resort, you can downgrade to our v9.x release line and use the SDK-provided component but, this isn't what we recommend when starting a new project.
