### ISSUE TITLE
Do not update the message in the channel preview when deleting the message.

### ISSUE THREAD

**Issue by vihan85** [GetStream/website-react-examples#87]
**Describe the bug**

Do not update the message in the channel preview when deleting the message.

**To Reproduce**

https://github.com/GetStream/stream-chat-react/assets/104440194/80061708-d581-4f59-9e72-a43a00a1eaca

**Expected behavior**

**Screenshots**

**Package version**
- stream-chat-react:
- stream-chat-css:
- stream-chat-js:

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MartinCupela** [comment]
fixed by: #88
